### PR TITLE
mediatek: skip bad blocks on SPI-NAND (SNFI/SPIM-NAND)

### PR DESCRIPTION
**Pull request by dangowrt**
In case we don't use NMBM in favor of using UBI on highler layers we still need to handle bad blocks while reading BL3 image from SPI-NAND flash. Ideally we would be using UBI here as well, e.g. by porting drivers/mtd/ubispl/ from U-Boot sources (under BSD-3-Clause).

For now, apply a generic minimal solution sufficient skipping up to 3 bad blocks while reading which is sufficient for loading BL3 even from a very broken NAND.

Signed-off-by: Daniel Golle <daniel@makrotopia.org>

### CODE REVIEW

**Comment by dangowrt** [comment]
See also [OpenWrt Forum thread](https://forum.openwrt.org/t/belkin-rt3200-linksys-e8450-wifi-ax-discussion/94302/2621?u=daniel)

**Comment by hackpascal** [comment]
the spim-nand nand_read() already supports skip bad block. I'll upload a new version for snfi-nand

**Comment by dangowrt** [comment]
Excellent. Thank you!

**Comment by dangowrt** [comment]
Superseded, now implemented directly in snfi driver.

**Pull request closed without merging**
